name: Generate Snake Animation

on:
  schedule:
    # Se ejecuta cada 6 horas
    - cron: "0 */6 * * *"
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    # ¡SOLUCIÓN 1! Añadimos esta sección de permisos
    # Esto le da permiso al bot para escribir en tu repositorio
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      # ¡SOLUCIÓN 2! Usamos la versión 3 de la acción que es más moderna y no da la advertencia
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          # Genera el SVG con las contribuciones
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

